/*======================================*/
/*
THIS FILE WAS GENERATED BY CHAT-GPT
*/
/*======================================*/


function populateDashboard() {
            const baseRevenue = 65000 + Math.floor(Math.random() * 20000);
            const monthGrowth = 0.02 + Math.random() * 0.08;
            const users = 1500 + Math.floor(Math.random() * 600);
            const signups = Math.floor(users * (0.03 + Math.random() * 0.04));
            const conversion = ((signups / users) * 100).toFixed(1);

            document.getElementById('rev').textContent = '$' + baseRevenue.toLocaleString();
            document.getElementById('rev-trend').textContent = '+' + (monthGrowth * 100).toFixed(1) + '% vs last month';
            document.getElementById('users').textContent = users.toLocaleString();
            document.getElementById('users-trend').textContent = '+' + (Math.random() * 10).toFixed(1) + '% vs last week';
            document.getElementById('signups').textContent = signups;
            document.getElementById('signups-trend').textContent = '+' + Math.floor(Math.random() * 30) + ' since yesterday';
            document.getElementById('conv').textContent = conversion + '%';
            document.getElementById('conv-trend').textContent = conversion > 4 ? 'Up slightly' : 'Stable';

            // Activity table
            const tbody = document.querySelector('#activity-table tbody');
            tbody.innerHTML = '';
            const actions = ['Logged in', 'Updated profile', 'Uploaded file', 'Commented', 'Joined group'];
            const statuses = ['Success', 'Pending', 'Failed'];
            for (let i = 0; i < 6; i++) {
                const user = 'User ' + (1000 + Math.floor(Math.random() * 9000));
                const action = actions[Math.floor(Math.random() * actions.length)];
                const date = new Date(Date.now() - Math.random() * 6 * 86400000).toLocaleDateString();
                const status = statuses[Math.floor(Math.random() * statuses.length)];
                tbody.insertAdjacentHTML(
                    'beforeend',
                    `<tr><td>${user}</td><td>${action}</td><td>${date}</td><td>${status}</td></tr>`
                );
            }

            // Traffic chart data
            const ctx = document.getElementById('trafficChart');
            const days = Array.from({ length: 14 }, (_, i) => {
                const d = new Date();
                d.setDate(d.getDate() - (13 - i));
                return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
            });
            const trafficData = days.map(() => 200 + Math.floor(Math.random() * 150));
            const baseColor = getComputedStyle(document.documentElement).getPropertyValue('--chart-color') || '#0074d9';

            new Chart(ctx, {
                type: 'line',
                data: {
                    labels: days,
                    datasets: [{
                        label: 'Daily Visits',
                        data: trafficData,
                        borderColor: baseColor,
                        backgroundColor: baseColor + '33',
                        tension: 0.3,
                        fill: true,
                        pointRadius: 3
                    }]
                },
                options: {
                    responsive: true,
                    plugins: {
                        legend: { display: false }
                    },
                    scales: {
                        x: { grid: { display: false } },
                        y: { grid: { color: '#eee' }, ticks: { stepSize: 100 } }
                    }
                }
            });
        }

        document.addEventListener('DOMContentLoaded', populateDashboard);